In [70]:
import pandas as pd

df = pd.read_json("Office_Products_5.json", lines=True)

In [71]:
df.head(1)

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A32T2H8150OJLU,B00000JBLH,ARH,"[3, 4]","I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling. I searched for another one to replace it, but found one difficult to come by in my area. So, I decided to buy up and purchased an HP 49G. What a mistake! I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best. The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you. It's programmable. It does basic statistics well, and many business applications too. The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend. I didn't even have to replace the batteries in well over a decade of use!HP 12C, I'm coming home!",5,"A solid performer, and long time friend",1094169600,"09 3, 2004"

In [72]:
df.dtypes

reviewerID        object
asin              object
reviewerName      object
helpful           object
reviewText        object
overall            int64
summary           object
unixReviewTime     int64
reviewTime        object
dtype: object

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53258 entries, 0 to 53257
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reviewerID      53258 non-null  object
 1   asin            53258 non-null  object
 2   reviewerName    52799 non-null  object
 3   helpful         53258 non-null  object
 4   reviewText      53258 non-null  object
 5   overall         53258 non-null  int64
 6   summary         53258 non-null  object
 7   unixReviewTime  53258 non-null  int64
 8   reviewTime      53258 non-null  object
dtypes: int64(2), object(7)
memory usage: 3.7+ MB

In [74]:
review_counts = df['reviewerID'].value_counts()          # most active first (default)
review_counts = df['reviewerID'].value_counts().sort_values(ascending=False)  # least active first

In [75]:
review_counts

reviewerID
A3OXHLG6DIBRW8           94
A22I55P15NSAOX           81
A1Z16630QMH8Q6           77
A1ODOGXEYECQQ8           76
A22CW0ZHY3NJH8           76
A3UW0PQLDUACMH           75
A26LQSC65AMTGK           71
A2068BC3ZXAVJQ           70
A1ZPY91VE3IDN1           66
A2LIPLT5LJTN5B           66
A28TWWUAWFVCTR           65
A18GJ9MYYO6GCQ           63
AEL6CQNQXONBX            60
A376OJHLE6SU9Q           60
A81XIM8XFKWX5            59
A2L6QS8SVHT9RG           59
AYB4ELCS5AM8P            58
A3J3OCM6PPWNRY           57
A2YKWYC3WQJX5J           57
A17771LTRWSKQ5           56
A3HPCRD9RX351S           54
A3SLC8F6VIWXIR           54
A13U975DFXBU44           53
A3963R7EPE3A7E           53
A3R5GTYQ50QVMD           53
A38BE06WWL20AY           51
A1EH2S92FHWZRP           51
A3NHUQ33CFH3VM           51
A1X3ESYZ79H59E           51
A2503LT8PZIHAD           50
ACJT8MUC0LRF0            50
A3HRDRQ5VAFPQS           50
A3EM243NDJ4DF3           49
A1FK6IQ111SJDR           49
A3VI2VETB90ZG5           49
A2QRXQPHDMFCQV           49
A1ILWPH1GHUXE2           48
A1ITRGMT80D5TK           48
ATFBVUXDIRXT6            48
A2BMZRO0H7TFCS           47
A1EVV74UQYVKRY           47
A5GPH59NDWJRB            47
A1POFVVXUZR3IQ           47
A1PAGHECG401K1           46
A3GS7OZXUEW48R           46
A11I1I9QLMAM1A           46
A1UQBFCERIP7VJ           46
AM18CU72YEWH5            45
A357B3PUHSVQA            45
A1RRMZKOMZ2M7J           45
A1INE33UQ1B4Q3           45
ARBKYIVNYWK3C            45
A2R1HUYHXV7H18           45
A100WO06OQR8BQ           45
A3F9CMU8KNAY1M           45
ADY836HK6QSYR            45
A2ZKQC0XCIIAEM           44
AVU1ILDDYW301            44
AUS5X6IMFLJBD            44
A32E5G5T902WRV           44
AV3XTMK5I2AWI            44
A25C2M3QF9G7OQ           44
A2R6RA8FRBS608           44
A1SORZL733985Z           44
A2KMV056844YV2           43
A2MNB77YGJ3CN0           43
A1F7YU6O5RU432           43
A3TAS1AG6FMBQW           43
AW5JSQCHC2ZJO            43
A34BZM6S9L7QI4           43
A2OCDK0BOW6UCY           43
ADLVFFE4VBT8             42
AQ6AGWKWMTY8H            42
A244CRJ2QSVLZ4           42
A3BZUQXA2QHDI2           42
A6FIAB28IS79             41
A3JUHP1E3WUHEA           41
A3NM1MT3Q2FHXV           41
A33YZNZIRA3H97           41
A2RMVKGPSIISC0           41
A1A9PD00UVHHVI           41
A3T8WOFS5RD2IR           41
A2BLFCOPSMBOZ9           41
A3MWP39R0W9TQX           41
A2HMF8ZR67BNZS           41
A1P2XYD265YE21           40
A27H0T39U3FZB5           40
A26BDXG9KVH7SU           40
A3EI4K5U61UZ7            40
A3U029B8Z5WGI2           40
A1X2LENOF84LCQ           40
ALNFHVS3SC4FV            39
AL6CEWLV2JB90            39
A2RQOO8VYAEZZG           39
A3FBM0RMCMAABV           39
A9GPCR9WJQCCJ            39
AN81JUYW2SL24            39
A2RX62V4E2BF5Z           39
AAA0TUKS5VBSA            39
A33Y8C4818EJL0           39
A1PI8VBCXXSGC7           38
A1IHK8GL1ESOND           38
A3H7NPNDMGLOU4           38
A2JXCOUGYS5Y4J           38
AFFVUZEGP1FDQ            38
A2QDOJFFLFGF18           38
A2I3XS9TO93Q0F           38
AGBFIQMV9L61Y            38
A2E1EFNIZL2FVA           37
A2AVMEB8PQOTTE           37
A3NG7X4APIV649           37
A1HRYC60VTMYC0           37
AC4XV78EJG1QB            37
A1IZJVLNMFACS6           37
ABQWMANK4AR63            37
A3M1PLEYNDEYO8           37
AY3D7DG5L5WCK            37
A141W8WHW9AC3H           37
A1VQHH85U7PX0            37
A11LNPG39A2ZV4           36
A319Y83RT0MRVR           36
A1HFT68GJ42LTM           36
A2OBDNQ5ZYU1L8           36
APP35M28G2U51            36
A23NSKTMSPPBTR           36
A1SCANWWQTEG9I           36
A1VYFEJM12ZP11           36
A194K60CWZ371J           36
A397CWU6DM3O5G           36
A16PUD6V3KAZ0Q           36
A2HTPS0JV3Q8ZD           36
A39GKCZWTMG27E           36
A2V5R832QCSOMX           36
A3HETHW2XD3DWH           36
A26LD9FQHTM8ZH           36
A34VRVI4CSI5RQ           36
A2SH6A32BE6NEV           35
A27X7XXOKMK879           35
A1BJOHHLG0D965           35
A2I4A4WGWII18Z           35
A2OS3TIVAKUAHG           35
A2SZLNSI5KOQJT           34
A19YOYY7FLQMA6           34
AHS6PX6H22WW1            34
A18LBGL7L9FEZV           34
A19FRW264WZTGP           34
A1GYEGLX3P2Y7P           34
A2VH0UT5EQFB6P           34
A30ODR6WBE61UB           34
A3A15L96IYUO6V           34
A10ZFE6YE0UHW8           34
A1KGNGL5KT3CJU           34
A2HPVNZZF15W93           34
ABDR6IJ93HFIO            34
A3S15YGZ6W6EV2           34
A10Y058K7B96C6           34
AK8LOFYRZJJW0            34
A3I1BJIFFM4S21           34
A36K2N527TXXJN           34
A36MP37DITBU6F           34
A2P739KOM4U5JB           34
A2HC9549CZAKNN           33
A2W0XCWOK3MW6F           33
A3FEGTOLCWXSV4           33
A250AXLRBVYKB4           33
A1VQBEW0G4IH1J           33
A38NELQT98S4H8           33
A3B9C6MZAFC1JX           33
A11T807LX2EF00           33
AOODNGLAEDN76            33
AG2YXYIQ8TLTA            33
A2DG63DN704LOI           33
AQIJ3ZEEVCIKU            32
A3VZH0PWLQ9BB1           32
A2UQIQUOAB47OT           32
A2L4ZGN7GZJ95T           32
ACQYIC13JXAOI            32
A3R33KMESG0XGQ           32
AEMSGB00FL3YO            32
A1RLP0R1N8H8C4           32
A2PD27UKAD3Q00           32
A35Q0RBM3YNQNF           32
A36A1ZYZH8568P           32
A23ZNGL704AW7O           32
A2PU80LCKRMC9X           32
A3IUW081KXD3PE           32
A3Q4TYJVAM4IRM           32
A1TS45JWJVOSSW           32
A278LEQK1TEPVB           32
A235UFZGCFN3J5           32
AB0Y33G717HOU            32
A35LT14WG5BX0T           32
AUV3OR951650C            32
A3LGT6UZL99IW1           32
A2BYV7S1QP2YIG           31
A2XU6J41ZQOJ2V           31
A3EPJSPH03AS29           31
A1UINGIK3UG77D           31
A1W415JP5WEAJK           31
A1D9V11QUHXENQ           31
A2TXMYYGSZCSZ1           31
AHFGCH8LANEZK            31
A2FRFAQCWZJT3Q           31
A22PUBSSNP54L            31
A1NS6O584WD5FJ           31
ACZ4YI6UWRVOG            31
A10ZBR6O8S8OCY           31
A3JPFWKS83R49V           31
A3HQAPXAJV7PRX           30
A13WOT3RSXKRD5           30
AFDJGY68CQL2X            30
A3RR2P5IS3DGPR           30
A2D1LPEUCTNT8X           30
A6HOWM08PLFZ5            30
A1F1A0QQP2XVH5           30
A2NOW4U7W3F7RI           30
A3J3ZHGDUDPCFL           30
AY6A8KPYCE6B0            30
AGVWTYW0ULXHT            30
A3R9X003XW0LNR           30
A16RI68PS6T5CA           30
A1H7Y5XKPGT0OS           30
A1VGXHHR08G044           30
AUCIFMWP3DU8R            30
A11OTLEDSW8ZXD           30
A3D9NUCR4RXDPY           30
AQYYUN3T7B0WM            30
A2ZJPDH0YP90SD           30
A23WE733QT4WGJ           29
A1ZZR25X0CNOJX           29
AJQDIT55SZ3ZX            29
A3CHIF3EHXCLA5           29
A2CNGARED6OWWU           29
A6SZZSMX7DQG1            29
A3W4D8XOGLWUN5           29
A8QYRG7TW491B            29
A22S7D0LP8GRDH           29
A1JZFGZEZVWQPY           29
AMRMK86X3PKXD            29
ADEZOPMPKK146            29
A19NP8YYADOOSF           29
A3T4OHEAHOJ700           29
A1FPQ54AIB26L0           29
A3CON4WD5PKNWO           29
ARXU3FESTWMJJ            29
A3OW12V8O7G5LD           29
A1J75JJ0Q2OEJN           28
A28RSMADFCBJDT           28
A55PCTJ6NINET            28
AEC90GPFKLAAW            28
A2PSC7LUNIDEAH           28
A226VGZWOEBPGL           28
A3LH77PBDFEO3F           28
A226GFM0Q9L37H           28
A1CMD08Z49PGKQ           28
A3TA0BXR9SKJB2           28
A1UG4J8DEG9NVW           28
AGOH8N902URMW            28
AYNAH993VDECT            28
A19XMHRB3G4DIR           28
A3HPFC4WMB2LZD           28
A1QVFHPY8418HC           28
A1ZCSSCAGBCD49           28
ABUE0ALHKWKHC            28
A1JFNZ4UAMEZN3           28
AJ8SVXL3SJN7T            28
A2XRZV63X79YSJ           28
A1URXSRV6WDHVY           28
A12E0Y0J6584RT           27
A1Z54EM24Y40LL           27
A18NS2LFYCLOTH           27
AMS2CPERWN7JV            27
A1BT6TL7UCIC5Y           27
A2MUGFV2TDQ47K           27
A8WAYVOKYBLO6            27
A1MZL91Z44RN06           27
A1MIWY5P4X6M4            27
A2VWE5SGNDS8HW           27
A2X06FP2PQ6EK0           27
AGHIUO1B3IF8H            27
A1XVF5DU3N05OM           27
A3U5CZ3PV82JXD           27
A1Z7Y2GMAP9SRY           27
A2YQ2ZI65F37N8           27
A3EJ8XHVDC0CWH           27
A3BVN2QBNPBHCR           27
A3CW0ZLUO5X2B1           27
A3LMPD1ZQTWOC4           27
A23GFTVIETX7DS           27
A14DNCG5WHM86Z           27
A14JBDSWKPKTZA           27
A26EQ8U96JA92T           27
A32T2H8150OJLU           27
A30IP3E4MDQ36            27
A2G04D4QZAXL15           27
A2BCDZO1XQLDH            26
A312UBIOP091MH           26
A1RFZGWX46N8H7           26
A2W9I628I6SE1U           26
A23KACXOE9O9TX           26
A2C66ZWC2V5FES           26
A1JUBRIZMO0RJV           26
A2MBLVMVDLHK1L           26
A3A1OA237FOZFK           26
A1OMXVXXP07F05           26
A32EOHLFZYXJEP           26
ATDE9JYCPI0L1            26
A1IH42TUIZ2XJL           26
A1Q1T811N4IY3Z           26
A1FDSZISWIXH1A           26
A3U41ZL33SS92P           26
AHN86VFJIJ2JP            26
A1IU7S4HCK1XK0           26
A37IHRVO8JWYF2           26
AV1F8VNJPLPTL            26
A2XA8CW5DF4MNZ           26
A2EHYCA29NSQLU           26
A2AF0NOCM71J0B           26
A1T61QP7QHYBRQ           26
A19UTUEBWKIZFT           26
A140ICK18NAAYR           26
ANTN61S4L7WG9            26
A2UOHALGF2X77Q           26
A34GZPHWYPSY2T           26
A4D5B7Q8A7PA6            26
ALQ4USPEQ9L5N            26
ALSAOZ1V546VT            26
A1ONZ8JRPLBNUI           26
ASFW4ZMNZJKDA            26
A27QXQQOLAMRRR           25
A21EDMG94ID7D            25
A3EZFFPVS34AMO           25
AO9UNKQG83BUP            25
A14MSHFCXPARFS           25
A2KQT4D0OZR569           25
A3DOPYDOS49I3T           25
A2TGMGZ116G6AW           25
A28X7NZ02016FO           25
A1IUTYIY6PW8DU           25
A45S6D1P309G9            25
A1M1Y5UGONAW06           25
A5JLAU2ARJ0BO            25
A2VIUUWR7B11KS           25
A16AXQ11SZA8SQ           25
A3QL857ALV5RCJ           25
A2BPB05QNCE00B           25
AR74YY08IP2WE            25
A3VBXQKRM7A4JR           25
AQY5XBYSENNZQ            25
AYWHCM0TJ4737            25
A1ZU55TM45Y2R8           25
A2I5LVVQ7WXEH6           25
A265NE6H6LYX87           25
AS44QEHT3KSPK            25
A16Z2OECAUX8Z4           25
AQZ4PHIEEV5N5            25
A34W7QA4J5UTOR           24
AIBRTGBN07D6A            24
A2OKRGHIYTBQ6P           24
A2MSQNPTNAAGL1           24
A2ULQOGN59LDNK           24
AR33KU52LIBF1            24
A3EXWV8FNSSFL6           24
A1WXG10FJ353K0           24
A17V9XL4CWTQ6G           24
A1A535TCGNMVPI           24
A1T2ZO4ARVSUGE           24
A1W4F91DH3XPB2           24
A1DW1FK1H3F2TM           24
A1SY4X1WWNOBX5           24
AZKGCE3LNX7WB            24
A37R3P5JFNQG8S           24
A3MFORLOKIOEQY           24
A1PL7QILVQV3IF           24
A3NOBH42C7UI5M           24
AT53ZTTO707MB            24
A1E5WXNTI7EO2A           24
AM2IR1V5EU55U            24
AG71XMQGQ2UTJ            24
A2IFKH3TJ10387           24
A1FDVT0DLJWV78           24
A1IA0O3OYQO9LV           24
A301B6L3TCD7WL           24
AGVDI7RLT24WJ            24
AW2BZYHG2MGSN            24
ALEUQQE118NEW            24
A3CVC8TCHFFDK8           24
A37MH7ICH80QOX           24
A3AHDR4F2J7YXX           24
A12DQZKRKTNF5E           24
A1TR1R2QKWRSRA           24
AE12AEJFCOGGY            24
A3IMK08UX0I46A           24
A2AMTEB5UZEOXE           24
A3EFSLEMHNPP6A           23
A37RIRXE3WECZ            23
A1B6SIX2I161O9           23
A1MRRMHGV3PN5W           23
A38RMU1Y5TDP9            23
A2OL5WLCNZVD9K           23
A2KMY4RVMJ1EP6           23
A19WEEGB05YAZ3           23
A3K5NP63E32ZBG           23
A1XJOSJN6FHFO0           23
A2EDTVVR9IFNLW           23
A3QS4WWC1LCA6H           23
A3DZFEICHK5LF2           23
A3R7RE5O61M112           23
A2VHCA21QKNEKE           23
A3CJ7MHAS9IMAM           23
A3PD8JD9L4WEII           23
A38ON1MOZNBCGE           23
APPCJX62WKIIP            23
A2NML53YCHS80S           23
A3KZEGBTPH6MMF           23
AXLN36UV9KGXD            23
AGJRUK27RBVYS            23
A2ZJMLZ1IA2YA9           23
A3FKGKUCI3DG9U           23
ANHL7BB84WJMF            23
A240FRPD4MEXND           23
A2HHAV29CZ1OIE           23
A3COBFLNYK52TE           23
A173YMJ9XFVRSY           23
AGFW667QNHDOY            23
A3BKNXX8QFIXIV           23
A293HA28PN3VO4           23
A1F9Z42CFF9IAY           23
A3I5YPJZMTG1QO           23
ACR4HKUT808U1            23
AQCJWSMSURQI2            23
AYOMAHLWRQHUG            23
AWJBO5XGIW8ZS            23
A1O97WKID9L3IA           23
AT28RL25Q2OLK            22
ALDAF4VVLFRHP            22
ACSX5AIZE3MJ9            22
A3DGJMO6VPG6FJ           22
A2OW356OMJNAVH           22
A9KAY47NCPQS             22
A2AC6GQ24S45GA           22
A3B20R4ZAH0Y2Y           22
A1BMG34CO5CMZ5           22
A1LKOIZXPQ9VG0           22
A2K3J2X8KDY47N           22
A680RUE1FDO8B            22
AQM0K7MBBT4AY            22
AZD8SMNGQI98O            22
A2SH7OWE8QJYNC           22
ACAXV4V8PBCE3            22
A34CSXOGVYF94S           22
A21BVL7PKG9BX8           22
A1J5HIF41ENSMZ           22
A39E7IWNHY62JT           22
A353U0L2HAMSHV           22
AFO678EAGH4Y9            22
A1X1CEGHTHMBL1           22
A1E1LEVQ9VQNK            22
A3TPNC3TKGCCEI           22
A156P4FPL8OGXB           22
A2RLLC0EGSXPPR           22
A209G57KXCBF4C           22
A3S5EXYZDEBF3K           22
AWPODHOB4GFWL            22
A7C77J4MH94B6            22
A37WVR9M1STQDU           22
A3G7BEJJCPD6DS           22
A2AYJJAFNSGSU1           22
A3SMD3T0QTN109           22
A2V0I904FH7ABY           22
A2NPF1LZ1S57JV           22
A1OWRLSD7LTSQ9           22
A31Z48BHHUTB0P           22
A1QK0XCAPHIW1L           22
AGB7UQZMVHNUJ            22
A1FDV3WPOHREY9           22
A3R1WFO4KIUQXZ           22
A9NXTC0HTPSDO            22
A2V92F5R7MLCVI           22
AX329NHW6B7BA            21
A3HJHV83O2U8BL           21
A1Y32FBX45NCNL           21
A15D2X8MICR2VQ           21
A2KOV8XWZOZ0FQ           21
AZ9WQM7SLUX7E            21
A20CQ20J30DJZT           21
A35JP8KSV9281K           21
A2XFM8PN6G0B02           21
A17O9AHKHK66AI           21
A2JKM8KF3296CW           21
AHRNDSKWH1YBT            21
A2TTHN1UMO82VY           21
A8INT3NMHRUS4            21
A188JOXWF4EY1R           21
AR3EVUQF0AC7R            21
A3094EPI56GKZ6           21
A30UP2KKD5IQEP           21
A4WEZJOIZIV4U            21
A3HUC8541SJ6UT           21
A1ACM1CBGORBN1           21
A9KLAL1CXZ0W5            21
A33PVCHCQ2BTN0           21
A1GQRGB8FGSLIZ           21
A34H90POFYRHGT           21
A2XCCN239AR1XK           21
A2S26YGSVXBCFL           21
A4UKBG3M5U5TI            21
A2UKE7GIVC7XFW           21
A2Q8GFSEUSGJ51           21
A2WB4OWBUH2VQX           21
A105S56ODHGJEK           21
A3KCKECEO3E2AN           21
ACYR6O588USK             21
A1LAGS8H4A2DR7           21
AFHYEO3Y1IIDD            21
AQH1SWR5HA413            21
A2SQJPUCZNHMZE           21
A29QCPFDSDNNKQ           21
AZMY6E8B52L2T            21
A3Q1J68QY1MZQ9           21
A2FLJCJ3SW0TUY           21
A33230MIA3W7G4           21
A2JNO9OR8FGNR4           21
A3IR834T7AROBT           21
AO09RWV40IX78            21
AHQ13I9CI4US6            21
A1YVO5V1SO18DZ           21
A2OW1FKQFPIA5D           21
AHIK7BUXFRMT8            21
A29VG90T649CSU           21
AYGEP8I4BQ3CK            21
AQ1F3NP2G15S5            21
A2RIAXGSBP65BJ           21
A39Q9G7J70A056           21
A30X750M8V1XXW           21
A1RFQVHBKVN4TA           21
A688RIZ2POWSQ            21
A3091RP0SPZLMN           21
ARIDN94LOCQFD            21
APDPA11IZPYLN            21
A1IQV6AI7L9NOK           21
A3KZ7OH4VRL048           21
AOVROBZ8BNTP7            21
A3NEAETOSXDBOM           21
A2I5QH4F5FDKK5           21
A2C1Y5F8DE9H6P           20
A1QBOC76MIOJYP           20
A2PK64OVZA1U8Z           20
A7OXU4EOFTXOB            20
A203OCQQ12MAVT           20
A2VDZ27CMLJVVH           20
A343C98QJO0JBE           20
A3MQ15651KGVLJ           20
A1UQUDT2Q0YENM           20
AHKPZ11JT110F            20
A3R9H6OKZHHRJD           20
A3OSHB0AACYN95           20
A3TB9HNQR54B5V           20
A1S27P7KJO9I96           20
A2877AOHJFZI0E           20
AF3BYMPWKWO8F            20
A3EXW4HNYX7HF5           20
A2TVJ0YDW3QO63           20
A32DYU82G6X3AO           20
A8EBWQZIDKF78            20
A3FBMSWBJ202SF           20
AEJAGHLC675A7            20
AJ86MYUT3VJE5            20
AXNJFYJRDK7CJ            20
ADFLPF6FI3W0O            20
A3QDDEW6RXVEAY           20
A1AZ1NXGGP6LDX           20
A1Q7A78VSQ5GQ4           20
A26SO3TOT2TLJE           20
AGEKVD8JPZQMT            20
ARPB88E6F2MFR            20
A3CG6YLYZJXQG4           20
A28I19Q54MYXGV           20
A26X7W5UM5QFT4           20
A12ENBT314RFXR           20
A6SM104267C1C            20
A21TCOLZEFE1AQ           20
A2BXMHV2B0QRCM           20
A27H9DOUGY9FOS           20
A2T5R4NOTKFBQV           20
A2YV6F6DLENNTM           20
A2TVH2OBNXYXHV           20
A2GHU8I0P3HFRW           20
A2JAEZ0FMAMJVW           20
A2OWR5G2OAQF7C           20
A28ZDVY6NV75P            20
A1AC1ZXX9IBCTT           20
A22VNXHU6IZ5MT           20
A15CL28ALB7MTZ           20
A1WBEIH7Z37LN9           20
A2FRKEXDXDN1KI           20
A2X3L31KCXBHCL           20
A13XQPWNCS2CHP           20
A1XOVR4ONAUEJ8           20
AKCZIJ6ZHE41D            19
A30J7WQV0ZNRXG           19
A3T7V207KRDE2O           19
A20DDH4NT6Q1E8           19
A3A90CELVLOUP6           19
A3JLGYV7IN38YN           19
A1PZW5JKLA85F1           19
A279A4Y2N1CQ26           19
A2Z3KC2BTCLPL4           19
A2GPQZHM465OUK           19
A34UVV757IKPVB           19
A3F3B6HY9RJI04           19
A2RHV42BTJSVON           19
ASFP250F22MDZ            19
A1UMSB7LAW0RIR           19
A30R8VFR16RE32           19
A1Z0LTKUA6F94D           19
AY1EF0GOH80EK            19
AD0WUBKBO21KK            19
A2GPLOLLE6BUDT           19
A34DQINHT6NYJU           19
A3T1LD0C65QCWK           19
A1FYYHVUDAYU53           19
A3EOVXI1VZIHUQ           19
A2LW5AL0KQ9P1M           19
A2705TYWNRS495           19
A70NFM6KHU24F            19
A2QR043WBXXX6L           19
ASJLXOX1VD4DF            19
A230PPNNJYJ6HR           19
A1XZP6VNRUN0K1           19
A3R19YKNL641X3           19
A4BNJSZVARL5W            19
AUAX1QWUCYKSX            19
A1FVP6G8W3O8ZA           19
AQ8DU6XVA3USJ            19
AKMEY1BSHSDG7            19
A3F2926FPOBNL            19
A2065HBMYDXJ1S           19
AJ6H9ZV7TJUUT            19
AJV985MKGCIQ0            19
A13BX9O5UDBILC           19
ABC68JUCPTVOE            19
ATLO3YXU2BC16            19
A16YU3GRGCD95S           19
A1YJMG0QJXZLD4           19
AI43VKPN5NF7D            19
A3IAU6ZPVF2R5K           19
A3NDUBKYPI47N2           19
A1CVFUQ1PGSIJL           19
A2MCC0XFURU2K2           19
A2YQICWD7C1F9U           19
A1E8XXAKINL0B1           19
A31AVXMESQRQAC           19
A36TDLV6OK3RO3           19
A3U52V5ZAHZZKU           19
A3M7R4PD0FEPUB           19
A3CHMHGSJSQ02J           18
A2YB7DLC3FOR7W           18
A2AAHDM93LC9BI           18
A18OLZIT0DGVJR           18
A2E2PA6UNK1E05           18
ALRCAGJOJ9583            18
A36IHC0K68NS2            18
A1VUN4JU731CBH           18
A2UW9WI22QKMZE           18
A2QL3AISOKZCX3           18
A2L35P0VQE7LBN           18
A2RWHTNM5P3I8Y           18
A221I9R7I92ORO           18
AXR3CV6A4FMBG            18
A1NN8Q1DLAYPGH           18
AUITG1DJ3QUGK            18
A7UPJYPAH73NC            18
A3V6Z4RCDGRC44           18
A20F84KUBWM88B           18
AK1WNXTHNCG5V            18
A4SD8F79JBYG2            18
A1TP2RW7KDI5AZ           18
A1DC1O4VX6AHPP           18
A1M7Y63Y5GYJI1           18
ATOKT8QYK967L            18
A2H0T0PY5IMEFX           18
A3OC93X866Z8TB           18
AFZJNYR931ZCN            18
A2B7BUH8834Y6M           18
A3GMRYV7VAYK5Q           18
A3LZA0ZL5IA0MS           18
A10G4BPT5MGBHY           18
A3RGHO0Q938FRS           18
A1YCQHS3N8E8UE           18
A3TIJLY4VX8CH3           18
A2U0LY01LK9C3E           18
A1J6B00Z1D6PS4           18
AFYQ9V4XBVCJ1            18
AK9FTWLCW09RR            18
AFICF7DKHTQ87            18
ATANE2SC44592            18
A19EKT8H85AKO5           18
A2I98OOPNIJNYY           18
AQB4DH57MSZSC            18
A3VWGPUMJMVD1I           18
A3D5B2CBFNJB0K           18
A1H88L8X6HM1BQ           18
A2LAS014NSRW72           18
A39H1GO9E3YQIB           18
A28YBL28P03P8V           18
A2MY9VXHZYAHUZ           18
A2561PYW9TTMYD           18
AKE6DXEN3GWPC            18
A204KVEV30UDE2           18
A3CBCVHIK3G76X           18
A18FUHNBP90IB4           18
A1ZGXZW37JEZWH           18

In [76]:
df[df['reviewerID']=='A3OXHLG6DIBRW8']

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
838,A3OXHLG6DIBRW8,B00004Z6NA,"C. Hill ""CFH""","[0, 0]","The Epson High-Gloss Premium Photo Paper is very high quality inkjet paper that produces fantastic looking, smudge resistant prints from myEpson Stylus Photo 2200 Inkjet Printer.This paper is very quick drying so prints can be stacked without worrying that they will stick together. I also like that it is fairly heavy stock so prints have the feel of professional lab quality.Highly Recommended!CFH",5,"High Quality, Quick Drying Photo Paper - Highly Recommended",1254614400,"10 4, 2009"
881,A3OXHLG6DIBRW8,B000050FZP,"C. Hill ""CFH""","[3, 3]","The AT&T; Trimeline is a very basic corded phone that works when the power goes out. We bought three of these (one for our house, shop, and my mother's house) to use mostly as backup for when our various cordless phones become unusable in during power outages (more frequent than I like in our area).We have these connected to line splitters (likeBelkin RJ11 Plug/2-RJ11 Jack Modular T Adapter) and they work just fine. These also have physical switches to adjust the ringer volume and phone volume which, although limited, does give us some control. It is also handy that the keypad is ""backlit"" and draws power directly from the phone line, allowing you to see the numbers in the dark.While these phones do have the ability to store numbers and even speed-dial, we have not set them up to do it.Highly Recommended!CFH",5,Handy For When The Power Goes Out - Highly Recommended,1284768000,"09 18, 2010"
1060,A3OXHLG6DIBRW8,B00005C3YY,"C. Hill ""CFH""","[7, 10]","This Matte Finish ""Magic"" Tape is so much better than the generic types for most uses. It goes on totally clear on most paper, it is very strong, and the matte finish doesn't easily reflect light so it doesn't draw attention to itself.The brand name ""Scotch"" has become a ""proprietary eponym"" for this type of clear tape, along the same lines as Band-Aid, Kleenex, and Saran wrap for their respective products. This generally happens only when a product is the best of its kind and has become the de-facto standard. This is certainly the case for Scotch Tape.It may cost a little more, but it generally worth it. Highly Recommended!",5,Its Scotch Tape! Highly Recommended!,1252022400,"09 4, 2009"
1084,A3OXHLG6DIBRW8,B00005C55O,"C. Hill ""CFH""","[0, 0]","This Mead Filler Paper is fairly standard, if just a little thinner than higher quality notebook paper. This is a decent deal as an add on product with free shipping.Recommended for casual writing needs.CFH",4,Notebook Paper - Recommended,1404604800,"07 6, 2014"
1171,A3OXHLG6DIBRW8,B00005MITU,"C. Hill ""CFH""","[0, 0]","The AT&T; Trimeline is a very basic corded phone that works when the power goes out. We bought three of these (one for our house, shop, and my mother's house) to use mostly as backup for when our various cordless phones become unusable in during power outages (more frequent than I like in our area).We have these connected to line splitters (Belkin RJ11 Plug/2-RJ11 Jack Modular T Adapter) and they work just fine. These also have physical switches to adjust the ringer volume and phone volume which, although limited, does give us some control. It is also handy that the keypad is ""backlit"" and draws power directly from the phone line, allowing you to see the numbers in the dark.While these phones do have the ability to store numbers and even speed-dial, we have not set them up to do it.Highly Recommended!CFH",5,Works Even When The Power Is Out - Highly Recommended,1284768000,"09 18, 2010"
1303,A3OXHLG6DIBRW8,B000067V0A,"C. Hill ""CFH""","[2, 2]","The Epson Photo Stylus 2200 is a truly impressive photo quality inkjet printer. We recently bought a used 2200 to use in our small business for printing product pictures and custom images for retail sales on very heavy card stock. The results have been nothing short of amazing!The main features that made this the right choice for us were:+ Individual ink cartridges - saves money in the long run since you only replace the ones that are empty (a good deal can be found hereEpson 7 Color Ink Set with Photo Black for the Stylus Photo 2200 Inkjet Printer.)+ Accepts Very Thick Card Stock - using the rear feed port+ Outstanding Prints - the output is nothing short of amazingMy only complaint is that the rollers do need to be cleaned on occasion, but good instructions are found in the user manual. Hint: if you don't have the cleaning pad that came with the printer, use a bit of a cotton material wrapped on the thin edge of a ruler.Vista drivers (both 32 and 64 bit) can be downloaded from the Epson website.This is a very good printer and they can now be found for a reasonable priced on the used market! Highly Recommended!",5,Produces Fantastic Prints - Highly Recommended!,1254614400,"10 4, 2009"
2478,A3OXHLG6DIBRW8,B00006ICEM,"C. Hill ""CFH""","[0, 0]","These Wilson Jones Insertable Tab Dividers makes organizing our shop paperwork easy. These dividers are a little thin but they are not not in high physical stress area, so will hold up well enough in our office.Recommended!CFH",4,Works Well For My Needs - Recommended,1401321600,"05 29, 2014"
2752,A3OXHLG6DIBRW8,B00006IDV6,"C. Hill ""CFH""","[0, 0]","This Five Star Quadrille/Graph Ruled Filler Paper is very good quality, with easy to see grid-lines and appropriately sized holes. We play an &#34;old school&#34; RPG that requires a lot of mapping and scale drawing. This paper is perfect for our needs.Highly Recommended!CFH",5,Perfect For RPG - Highly Recommended,1404604800,"07 6, 2014"
3831,A3OXHLG6DIBRW8,B00006IFCX,"C. Hill ""CFH""","[0, 0]","These &#34;Oxford Ruled Index Cards, 3 x 5 Inches&#34; are fairly thin but certainly thicker than standard paper. These are blank on one side and have the normal index card lines printed on the other.These work well for my needs and were very inexpensive.Recommended!CFH",4,Thin But Functional - Recommended,1391558400,"02 5, 2014"
3880,A3OXHLG6DIBRW8,B00006IFHD,"C. Hill ""CFH""","[0, 0]","Shapie markers are simply the best permanaemt markers for just about any use. We use them for making quick signs in our shop, putting names on clothing (on the inside), and in the woodshop to indicate cut lines.They are also pernanent, so some care should be taken.Highly recommended!",5,Great Permanent Markers! Highly Recommended!,1244937600,"06 14, 2009"
4001,A3OXHLG6DIBRW8,B00006IFIR,"C. Hill ""CFH""","[0, 0]","We use this Expo 7-Piece Dry Erase Kit in our small business to keep track of our on-going projects. Here are my observations:Markers:+ The six colors allow us to color code priorities+ Positive cap seal keeps markers from drying out+ Relatively low odorEraser:+ Works well enoughHolder:+ Holds all of the markers and the eraser- Very thin plastic- Weak adhesive, used extra double stick tape to hold on the wallThis is works for our needs, with the good quality markers, good eraser, and usable holder.Recommended!CFH",4,Good For Small Office - Recommended,1326585600,"01 15, 2012"
4104,A3OXHLG6DIBRW8,B00006IFKU,"C. Hill ""CFH""","[0, 0]","This Swingline Standard Stapler is a good choice for home or light office use. This is a very basic stapler that works exactly as expected and should hold up well to normal craft, project, or homework duty.Recommended!CFH",4,Good Standard Stapler - Recommended,1404604800,"07 6, 2014"
4476,A3OXHLG6DIBRW8,B00006JNMK,"C. Hill ""CFH""","[3, 3]","Theses ""Post-It Index File Tabs"" are great little labels that come in a clever plastic dispenser. There are 66 labels, 22 each of Red, Yellow, and Blue. The sticky labels are easy to write on with pen or pencil and, while they stay put when placed, they are removable making them great for use as bookmarks.These are really handy labels that we have found dozens of uses for around the house and in our small business. Oh, and you certainly can use them to label files too (and we do).Highly Recommended!CFH",5,Handy Removable Color Tabs - Highly Recommended,1266105600,"02 14, 2010"
5198,A3OXHLG6DIBRW8,B000093L22,"C. Hill ""CFH""","[1, 1]","This Swingline ""Rio Red Business Stapler"" is very sturdy and well made, making this one of the better quality staplers I have used in long time. This is a good looking stapler and the bright red color makes it easy to find on my cluttered desk.The heavy weight of this stapler helps it to perform perfectly and it easily handled the eighteen page report I tested it on.Highly Recommended!CFH",5,Really Good Stapler - Highly Recommended,1314057600,"08 23, 2011"
5743,A3OXHLG6DIBRW8,B0000C0CIR,"C. Hill ""CFH""","[0, 0]","The Avery Dark T-Shirt InkJet Iron-On Transfers are a very cool product useful for putting your images on dark material where regular transfers will not work. Saddly, don't expect to use the whole page for your design.These perform exactly as expected, with great image quality and no problems feeding through my printer, right up to the point where you attempt to peel the backing off before ironing on the transfer. I spent a good 1/2 hour trying to remove the backing, using every trick possible before resorting to making a ""small"" rip (as the instructions suggest) to get it started. This worked most of the time, but it means that you can't use the whole sheet since you have to rip it to remove the backing. We learned to only print about 3/4 of the page to give us plenty of ripping space.After you get the backing off, these iron on to your cotton material and really do look great. Be sure to read and follow the directions.I'll look for another brand, but will continue to use these if a better solution isn't out there.",3,"Great Idea, Hard To Use!",1249862400,"08 10, 2009"
5907,A3OXHLG6DIBRW8,B0000TIMUG,"C. Hill ""CFH""","[0, 0]","We picked up this ""HP Everyday Photo Paper"" to print product pictures for my wife's small business on better quality paper than ""plain paper"". The end results are better than plain paper, but far below most other lower cost photo paper. Here are my observations:Pros -+ Inexpensive; for photo paper, this is relatively low pricedCons -- Slow Drying; myBrother MFC-6490CW Professional Series Color Inkjet Wireless All-in-One Printerhas fairly quick drying ink on most papers, but was really surprised that my prints smudged even after sitting for more than five minutes- Marginal Image Quality; no amount of tweaking I could do produced ""outstanding"" resultsWe will use the rest of this paper, but will not buy it again.CFH",2,SLOW Drying Paper - Not Recommended,1275004800,"05 28, 2010"
6383,A3OXHLG6DIBRW8,B0002VS6HG,"C. Hill ""CFH""","[0, 0]","These Brother DK-1201 Die-Cut Standard Address Labels work perfectly in my brother GL-700 printer. We use these to label products in our small shop and, on occasion, as address labels. The printer recognizes the labels and automatically provides the correct template for the label.This is a great system!Highly Recommended!CFH",5,Perfect - Highly Recommended,1383091200,"10 30, 2013"
6432,A3OXHLG6DIBRW8,B0003WN0DO,"C. Hill ""CFH""","[23, 23]","Shapie markers are simply the best permanaemt markers for just about any use. We use them for making quick signs in our shop, putting names on clothing (on the inside), and in the woodshop to indicate cut lines.The colors are bright and do not fade over time. They are also pernanent, so some care should be taken.Highly recommended!",5,"Great Permanent Markers, In Color! Highly Recommended!",1244937600,"06 14, 2009"
6504,A3OXHLG6DIBRW8,B0006B088W,"C. Hill ""CFH""","[10, 11]","We bought the Plantronics HL10 Handset Lifter to go with ourPlantronics CS-55 Dect 6.0 Digital Wireless Office Headsetand have been very pleased with both devices. Using the handset lifter give you the ability to answer calls directly from the wireless headset, which is good if you spend a lot of time away from the physical phone to which the headset unit is connected.Setup was amazingly easy, just following the directions allowed us to get this installed in just a few minutes on our very inexpensive no-name speaker phone.Like our Plantronics Headset, this has passed the test of time and I would buy a new one if it failed today.Highly Recommended!CFH",5,Still Working After 3 Years! Highly Recommended!,1272326400,"04 27, 2010"
6761,A3OXHLG6DIBRW8,B0006HVU8S,"C. Hill ""CFH""","[3, 4]","The ""Stanley Bostitch Standard Booklet Stapler"" is a very solid (read heavy) saddle stapler that makes binding pamphlets and booklets a breeze!This stapler is very well made and is mostly metal. No worries about this stapler shifting when being used since the rubber feet and weight ensure that this will not be likely to budge.We have not had any jamming problems or failures of any type.Highly recommended! For those looking for a very light use stapler for pamphlets and booklets, considerSPR01316 - Long Reach Stapler, 20 Sht Cap, Standard Staples,Putty/Black.",5,Very Solid Saddle Stapler! Highly Recommended!,1238371200,"03 30, 2009"
7415,A3OXHLG6DIBRW8,B0007KI6PE,"C. Hill ""CFH""","[2, 3]","The Brother FAX-575 is a fairly good, and inexpensive, home or small office FAX machine. The unit feels a little on the flimsy side, mostly due to the wire paper holders, but is good enough for most uses once in place.The 575 functioned as expected, able to send and receive FAXes, make quick copies with acceptable quality, and includes a phone handset. It does none of them as well as any one of my all-in-one Scanner/Printer/FAX devices, but it also takes up less room and is somewhat less expensive.This unit does go on sale fairly often and can often be had for less than the MSRP.Recommended for limited usage. You might want to consider getting an extraBrother PC501 Print Cartridge (Fax 575), because the one that comes with it runs out fast.",4,"Good Functional Fax, Try to Find it on Sale",1240185600,"04 20, 2009"
7450,A3OXHLG6DIBRW8,B0007L1VLO,"C. Hill ""CFH""","[0, 0]","We use these Bic Mechanical Pencils at home, in our small business, and for our high school age kids. These are fairly inexpensive so we scatter them all over ensuring there is always a working pencil at hand when needed and the colorful bodies make them easy to spot.The pencils work well mechanically with the lead being advanced by pressing the eraser top. These are #2 leads so they can be used on the standardized testing as well. The eraser is the hard white rubber type and it works well enough. As other reviewers have noted, the lead does brake fairly easily so a lighter pressure is needed when writing with these compared to a regular pencil.We buy several packs a year and will likely continue to do so until the kids are out of school.Recommended!CFH",4,Good For Students - Recommended,1312588800,"08 6, 2011"
7570,A3OXHLG6DIBRW8,B0007RXD7S,"C. Hill ""CFH""","[16, 16]","The Brother ""PC501 Print Cartridge"" is the refill for theBrother FAX-575 Personal Fax, Phone and Copier. The cartridge that came with the 575 ran out way too fast, so I suggest getting an extra one of these right away.The cartridge worked as expected and was easy to install in the FAX machine.This is a required component for the 575 FAX machine, so it is ""Recommended"" as it does what it needed.",4,"Works as Expected, Required For Brother 575 Fax",1240185600,"04 20, 2009"
7791,A3OXHLG6DIBRW8,B0009F3P3U,"C. Hill ""CFH""","[0, 0]","This Matte Finish ""Magic"" Tape is so much better than the generic types for most uses. It goes on totally clear on most paper, it is very strong, and the matte finish doesn't easily reflect light so it doesn't draw attention to itself.The brand name ""Scotch"" has become a ""proprietary eponym"" for this type of clear tape, along the same lines as Band-Aid, Kleenex, and Saran wrap for their respective products. This generally happens only when a product is the best of its kind and has become the de-facto standard. This is certainly the case for Scotch Tape.It may cost a little more, but it generally worth it.Highly Recommended!CFH",5,It Is Good Tape - Highly Recommended,1252022400,"09 4, 2009"
8187,A3OXHLG6DIBRW8,B000A3IAHM,"C. Hill ""CFH""","[1, 1]",This Casio FX-115ES calculator came highly recommended by my son's geometry teacher and it has proven to be a good choice. The calculator has an intuitive layout that makes accessing functions very easy and the 2-line display is convenient for entering long equations and reading the solutions.This is a very powerful calculator and is also a fairly good value!Highly Recommended!CFH,5,Very Good Student Calculator - Highly Recommended,1338249600,"05 29, 2012"
9224,A3OXHLG6DIBRW8,B000FHYZRW,"C. Hill ""CFH""","[6, 6]","The ""Brother PT-80 P-touch Electronic Labeling System "" is a very inexpensive and easy to use labeler. We bought this when it was in the ""Lightning Deals"", so got it for a very a good price indeed.Pros:Solid constructionEasy to useEasy to get consumables (label cartridges)Cons:Eats batteriesNo AC adapterOver all, highly recommend for household/light usage.",4,"Great Basic Labeler, But Power Hungry",1216944000,"07 25, 2008"
9299,A3OXHLG6DIBRW8,B000FPGP4U,"C. Hill ""CFH""","[2, 2]","The Kensington 33374 Wireless Presenter is exactly what I was looking for to untether me from my PC while giving PowerPoint presentations. I give quite a few presentations in both my ""day job"" and as an instructor in my wife's small business and I like to walk around when talking. This handy device is so easy to install (just plug in the USB dongle, windows did the rest) and use that I didn't even have to read the directions to get it working.The small unit fits comfortably in my medium sized hands and all four buttons are in easy thumbing position. The top button with the laser symbol can be used to start the presentation (it works like the ""F5"" key in any application) and also activates the fairly bright red laser pointer, the two middle buttons advance or backup the presentation (the ""Page Down"" and ""Page Up"" keys), and the bottom button ""Blanks"" the presentation (the ""b"" key). The range is very good and easily covers the room sizes I typically work in.I like that the USB connector is stored inside the body of the device and it shuts off the unit when inserted. It also uses standard AAA batteries and includes 2 Energizers to get you started right away.This is a well designed and easy to use tool that does exactly what I want it to do - Highly Recommended!",5,Great Presentation Aid - Highly Recommended!,1253664000,"09 23, 2009"
10498,A3OXHLG6DIBRW8,B000JCTH2Q,"C. Hill ""CFH""","[3, 3]","This pad of double sided 1/4"" ruled graph paper is great for school homework and sketching scaled layouts. I like that the pages pull cleanly from the pad, leaving a standard letter sized 8.5""x11"" sheet. The individual sheets of paper are a little on the thin side, so we have learned not to press too hard with a sharp pencil, but this is not really an issue when used in the pad.This is good for our household and small business graphing needs, recommended!CFH",4,Good For My Needs - Recommended,1317772800,"10 5, 2011"
10542,A3OXHLG6DIBRW8,B000JEAAP2,"C. Hill ""CFH""","[1, 1]","These are sturdy pencils that have strong leads and good erasers. I also like that the paint doesn't chip and flake with normal use. We use a lot of these #2 yellow pencils for our small business and with our two school aged kids, and never had any problems with the quality of these.Recommended!",5,Great Pencils - Highly Recommended!,1252454400,"09 9, 2009"

In [77]:
df.columns

Index(['reviewerID', 'asin', 'reviewerName', 'helpful', 'reviewText',
       'overall', 'summary', 'unixReviewTime', 'reviewTime'],
      dtype='object')

In [78]:
df.rename(columns={'overall': 'rating','reviewText':'review','reviewTime':'time'}, inplace=True)

**helpful is Amazon's way of storing how many people found that review useful — it's stored as a pair of numbers: [helpful_votes, total_votes].**

In [79]:
df.head(1)

,reviewerID,asin,reviewerName,helpful,review,rating,summary,unixReviewTime,time
0,A32T2H8150OJLU,B00000JBLH,ARH,"[3, 4]","I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling. I searched for another one to replace it, but found one difficult to come by in my area. So, I decided to buy up and purchased an HP 49G. What a mistake! I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best. The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you. It's programmable. It does basic statistics well, and many business applications too. The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend. I didn't even have to replace the batteries in well over a decade of use!HP 12C, I'm coming home!",5,"A solid performer, and long time friend",1094169600,"09 3, 2004"

In [80]:
df.dtypes

reviewerID        object
asin              object
reviewerName      object
helpful           object
review            object
rating             int64
summary           object
unixReviewTime     int64
time              object
dtype: object

In [81]:
df['new_time'] = pd.to_datetime(df['time'], format='%m %d, %Y')

In [82]:
pd.set_option('display.max_colwidth', None)   # show full text, no cutoff

In [83]:
df.head(1)

,reviewerID,asin,reviewerName,helpful,review,rating,summary,unixReviewTime,time,new_time
0,A32T2H8150OJLU,B00000JBLH,ARH,"[3, 4]","I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling. I searched for another one to replace it, but found one difficult to come by in my area. So, I decided to buy up and purchased an HP 49G. What a mistake! I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best. The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you. It's programmable. It does basic statistics well, and many business applications too. The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend. I didn't even have to replace the batteries in well over a decade of use!HP 12C, I'm coming home!",5,"A solid performer, and long time friend",1094169600,"09 3, 2004",2004-09-03

In [84]:
df["review_date"] = pd.to_datetime(df["unixReviewTime"], unit="s")


df["review_year"] = df["review_date"].dt.year
df["review_month"] = df["review_date"].dt.month
df["review_day"] = df["review_date"].dt.day
df["day_of_week"] = df["review_date"].dt.day_name()
df["is_weekend"] = df["review_date"].dt.dayofweek >= 5

In [85]:
df.head(1)

,reviewerID,asin,reviewerName,helpful,review,rating,summary,unixReviewTime,time,new_time,review_date,review_year,review_month,review_day,day_of_week,is_weekend
0,A32T2H8150OJLU,B00000JBLH,ARH,"[3, 4]","I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling. I searched for another one to replace it, but found one difficult to come by in my area. So, I decided to buy up and purchased an HP 49G. What a mistake! I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best. The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you. It's programmable. It does basic statistics well, and many business applications too. The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend. I didn't even have to replace the batteries in well over a decade of use!HP 12C, I'm coming home!",5,"A solid performer, and long time friend",1094169600,"09 3, 2004",2004-09-03,2004-09-03,2004,9,3,Friday,False

In [86]:
import requests
import json
import pandas as pd

In [87]:
url = "https://huggingface.co/datasets/McAuley-Lab/Amazon-Reviews-2023/resolve/main/raw/review_categories/Office_Products.jsonl"

rows = []
count = 0
MAX_ROWS = 53258   

with requests.get(url, stream=True) as r:
    for line in r.iter_lines():
        if not line:
            continue
        count += 1
        record = json.loads(line)
        if record["timestamp"] >= 1420070400000:  # Jan 1, 2015
            rows.append(record)
            if len(rows) >= MAX_ROWS:
                break

df_new = pd.DataFrame(rows)
print("done. final shape:", df_new.shape)

done. final shape: (53258, 10)

In [88]:
df_new.columns

Index(['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id',
       'timestamp', 'helpful_vote', 'verified_purchase'],
      dtype='object')

In [89]:
df_new=df_new.rename(columns={
    "user_id":"reviewerID",
    "asin":"asin",
    "title":"summary",
    "text":"review",
    "rating":"rating",
    "helpful_vote":"helpful_votes"
})

In [90]:
df_new["reviewerName"] = None        
df_new["helpful"] = None             
df_new["total_votes"] = None         
df_new["helpful_ratio"] = None

In [91]:
df_new["review_date"]=pd.to_datetime(df_new["timestamp"],unit="ms")
df_new['review_date'].head(5)

0   2023-03-04 14:15:45.945
1   2023-03-04 14:12:40.682
2   2022-08-11 03:33:51.933
3   2022-08-06 17:14:26.713
4   2022-08-06 15:23:10.978
Name: review_date, dtype: datetime64[ns]

In [92]:
df_new["unixReviewTime"]=(df_new['timestamp']//100)
df_new['unixReviewTime'].head(2)

0    16779393459
1    16779391606
Name: unixReviewTime, dtype: int64

In [93]:
df_new["time"]=df_new["review_date"].dt.strftime("%m %d %Y")
df_new["new_time"]=df_new["review_date"].dt.strftime("%Y-%m-%d")
df_new[["time","new_time"]].head(2)

         time    new_time
0  03 04 2023  2023-03-04
1  03 04 2023  2023-03-04

In [94]:
df_new["review_year"] = df_new["review_date"].dt.year
print(sorted(df_new["review_year"].unique()))   # should now show 2015-2023

[np.int32(2015), np.int32(2016), np.int32(2017), np.int32(2018), np.int32(2019), np.int32(2020), np.int32(2021), np.int32(2022), np.int32(2023)]

In [95]:
df_new["review_month"]=df_new["review_date"].dt.month
df_new["review_month"].head(2)

0    3
1    3
Name: review_month, dtype: int32

In [96]:
df_new["review_day"]=df_new["review_date"].dt.day
df_new["review_day"].head(2)

0    4
1    4
Name: review_day, dtype: int32

In [97]:
df_new["day_of_week"]  = df_new["review_date"].dt.day_name()
df_new["is_weekend"]   = df_new["review_date"].dt.dayofweek >= 5
df[['day_of_week','is_weekend']].head(2)

  day_of_week  is_weekend
0      Friday       False
1    Saturday        True

In [98]:
df.columns

Index(['reviewerID', 'asin', 'reviewerName', 'helpful', 'review', 'rating',
       'summary', 'unixReviewTime', 'time', 'new_time', 'review_date',
       'review_year', 'review_month', 'review_day', 'day_of_week',
       'is_weekend'],
      dtype='object')

In [99]:
df_new.columns

Index(['rating', 'summary', 'review', 'images', 'asin', 'parent_asin',
       'reviewerID', 'timestamp', 'helpful_votes', 'verified_purchase',
       'reviewerName', 'helpful', 'total_votes', 'helpful_ratio',
       'review_date', 'unixReviewTime', 'time', 'new_time', 'review_year',
       'review_month', 'review_day', 'day_of_week', 'is_weekend'],
      dtype='object')

In [100]:
df_new = df_new[
    ["reviewerID", "asin", "reviewerName", "helpful", "review", "rating",
     "summary", "unixReviewTime", "time", "new_time", "review_date",
     "review_year", "review_month", "review_day", "day_of_week",
     "is_weekend", "helpful_votes", "total_votes", "helpful_ratio"]
]

df_new.columns

Index(['reviewerID', 'asin', 'reviewerName', 'helpful', 'review', 'rating',
       'summary', 'unixReviewTime', 'time', 'new_time', 'review_date',
       'review_year', 'review_month', 'review_day', 'day_of_week',
       'is_weekend', 'helpful_votes', 'total_votes', 'helpful_ratio'],
      dtype='object')

In [101]:
df_new = df_new.drop(columns=["images", "parent_asin", "verified_purchase"], errors="ignore")

In [102]:
def black_friday_date(year):
    nov1 = pd.Timestamp(year=year, month=11, day=1)
    first_thursday = nov1 + pd.Timedelta(days=(3 - nov1.dayofweek) % 7)
    fourth_thursday = first_thursday + pd.Timedelta(weeks=3)
    return fourth_thursday + pd.Timedelta(days=1)

def get_sale_windows(year):
    bf = black_friday_date(year)
    return {
        "black_friday": (bf, bf),
        "cyber_monday": (bf + pd.Timedelta(days=3), bf + pd.Timedelta(days=3)),
        "thanksgiving_week": (bf - pd.Timedelta(days=3), bf + pd.Timedelta(days=4)),
        "holiday_season": (pd.Timestamp(year, 12, 1), pd.Timestamp(year, 12, 31)),
        "prime_day": (pd.Timestamp(year, 7, 11), pd.Timestamp(year, 7, 13)) if year >= 2015 else None,
    }

for col in ["is_black_friday", "is_cyber_monday", "is_thanksgiving_week", "is_holiday_season", "is_prime_day"]:
    df_new[col] = False

for year in df_new["review_year"].unique():
    windows = get_sale_windows(year)
    mask_year = df_new["review_year"] == year

    for col, key in [
        ("is_black_friday", "black_friday"),
        ("is_cyber_monday", "cyber_monday"),
        ("is_thanksgiving_week", "thanksgiving_week"),
        ("is_holiday_season", "holiday_season"),
        ("is_prime_day", "prime_day"),
    ]:
        window = windows[key]
        if window is None:
            continue
        start, end = window
        in_window = df_new["review_date"].between(start, end)
        df_new.loc[mask_year & in_window, col] = True

df_new["is_sale_period"] = df_new[
    ["is_black_friday", "is_cyber_monday", "is_thanksgiving_week", "is_holiday_season", "is_prime_day"]
].any(axis=1)

print(df_new[["is_black_friday","is_cyber_monday","is_thanksgiving_week","is_holiday_season","is_prime_day","is_sale_period"]].sum())

is_black_friday            0
is_cyber_monday            0
is_thanksgiving_week     809
is_holiday_season       4651
is_prime_day             282
is_sale_period          5707
dtype: int64

In [103]:

for col in df_new.columns:
    if col not in df.columns:
        df[col] = False if col.startswith("is_") else None

In [104]:
for col in df.columns:
    if col not in df_new.columns:
        df_new[col] = False if col.startswith("is_") else None

In [105]:

print("df columns:", sorted(df.columns.tolist()))
print("df_new columns:", sorted(df_new.columns.tolist()))
print("Match:", set(df.columns) == set(df_new.columns))

df columns: ['asin', 'day_of_week', 'helpful', 'helpful_ratio', 'helpful_votes', 'is_black_friday', 'is_cyber_monday', 'is_holiday_season', 'is_prime_day', 'is_sale_period', 'is_thanksgiving_week', 'is_weekend', 'new_time', 'rating', 'review', 'review_date', 'review_day', 'review_month', 'review_year', 'reviewerID', 'reviewerName', 'summary', 'time', 'total_votes', 'unixReviewTime']
df_new columns: ['asin', 'day_of_week', 'helpful', 'helpful_ratio', 'helpful_votes', 'is_black_friday', 'is_cyber_monday', 'is_holiday_season', 'is_prime_day', 'is_sale_period', 'is_thanksgiving_week', 'is_weekend', 'new_time', 'rating', 'review', 'review_date', 'review_day', 'review_month', 'review_year', 'reviewerID', 'reviewerName', 'summary', 'time', 'total_votes', 'unixReviewTime']
Match: True

In [106]:
df_combined = pd.concat([df, df_new], ignore_index=True, sort=False)
print(df_combined.shape)

(106516, 25)

In [107]:
df_combined = df_combined.drop(
    columns=[
        "time",            
        "new_time",        
        "unixReviewTime",  
        "review_day",     
        "reviewerName",    
    ],
    errors="ignore"   
)

print(df_combined.columns.tolist())
print(df_combined.shape)

['reviewerID', 'asin', 'helpful', 'review', 'rating', 'summary', 'review_date', 'review_year', 'review_month', 'day_of_week', 'is_weekend', 'helpful_votes', 'total_votes', 'helpful_ratio', 'is_black_friday', 'is_cyber_monday', 'is_thanksgiving_week', 'is_holiday_season', 'is_prime_day', 'is_sale_period']
(106516, 20)

In [108]:
print(df_combined["review_year"].value_counts().sort_index())

review_year
2000        1
2001        5
2002        5
2003       31
2004       71
2005       78
2006      102
2007      279
2008      567
2009     3158
2010     7006
2011     9187
2012     7797
2013    12391
2014    12580
2015     2714
2016     4541
2017     4656
2018     5420
2019     7849
2020     9246
2021     9878
2022     7446
2023     1508
Name: count, dtype: int64

In [109]:

print(df_combined[["is_black_friday","is_cyber_monday","is_thanksgiving_week","is_holiday_season","is_prime_day","is_sale_period"]].sum())

is_black_friday            0
is_cyber_monday            0
is_thanksgiving_week     809
is_holiday_season       4651
is_prime_day             282
is_sale_period          5707
dtype: int64

In [110]:
df_combined.head(1)

,reviewerID,asin,helpful,review,rating,summary,review_date,review_year,review_month,day_of_week,is_weekend,helpful_votes,total_votes,helpful_ratio,is_black_friday,is_cyber_monday,is_thanksgiving_week,is_holiday_season,is_prime_day,is_sale_period
0,A32T2H8150OJLU,B00000JBLH,"[3, 4]","I bought my first HP12C in about 1984 or so, and it served me faithfully until 2002 when I lost it while travelling. I searched for another one to replace it, but found one difficult to come by in my area. So, I decided to buy up and purchased an HP 49G. What a mistake! I know that many people view the HP 49G (now 49G+) as the flagship of the HP line, but for me that was a disaster.The 49G may be powerful, but using it is extremely counterintuitive...and the manual was sketchy at best. The 12C, on the other hand, does what I need in a way that makes good sense to me.If you are looking for a solid, reliable calculator, the HP12C may be for you. It's programmable. It does basic statistics well, and many business applications too. The manual makes sense; you will be up and running in short order.I'm ready to set my 49G aside and move back to my old friend. I didn't even have to replace the batteries in well over a decade of use!HP 12C, I'm coming home!",5.0,"A solid performer, and long time friend",2004-09-03,2004,9,Friday,False,None,None,None,False,False,False,False,False,False

In [111]:
df_combined[['helpful_votes','total_votes','helpful_ratio']].head(2)

  helpful_votes total_votes helpful_ratio
0          None        None          None
1          None        None          None

In [112]:
print(df_combined[["helpful_votes", "total_votes", "helpful_ratio"]].isna().sum())
print(df_combined.shape)

helpful_votes     53258
total_votes      106516
helpful_ratio    106516
dtype: int64
(106516, 20)

In [113]:

print(df_combined[["helpful_votes", "total_votes", "helpful_ratio"]].isna().sum())
print(df_combined[df_combined["reviewerID"] == "A32T2H8150OJLU"][["helpful", "helpful_votes", "total_votes", "helpful_ratio"]])

helpful_votes     53258
total_votes      106516
helpful_ratio    106516
dtype: int64
          helpful helpful_votes total_votes helpful_ratio
0          [3, 4]          None        None          None
3156   [104, 108]          None        None          None
4000     [47, 49]          None        None          None
4177       [0, 0]          None        None          None
7062       [1, 1]          None        None          None
7237       [0, 0]          None        None          None
7649       [5, 5]          None        None          None
8802       [0, 1]          None        None          None
9132       [0, 0]          None        None          None
10847      [0, 0]          None        None          None
12295      [0, 0]          None        None          None
12378    [18, 18]          None        None          None
14567      [0, 0]          None        None          None
17843      [3, 5]          None        None          None
19662    [12, 16]          None        None          None
24115      [0, 0]          None        None          None
31378      [1, 1]          None        None          None
32628      [0, 1]          None        None          None
35730      [1, 1]          None        None          None
39265      [0, 0]          None        None          None
40723      [2, 2]          None        None          None
41190      [0, 0]          None        None          None
43153      [2, 2]          None        None          None
46362      [0, 1]          None        None          None
48367      [0, 0]          None        None          None
50820      [0, 0]          None        None          None
50883      [0, 0]          None        None          None

In [114]:
df_combined["helpful_ratio"] = df_combined["helpful_ratio"].fillna(0)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_9924\2749154087.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_combined["helpful_ratio"] = df_combined["helpful_ratio"].fillna(0)

In [115]:


df_combined = df_combined.drop(columns=["helpful", "helpful_votes", "total_votes"], errors="ignore")

In [116]:
df_combined['helpful_ratio'].isna().sum()

np.int64(0)

In [117]:
cols = [col for col in df_combined.columns if col not in ["review", "summary"]]
df_combined[cols].head()

,reviewerID,asin,rating,review_date,review_year,review_month,day_of_week,is_weekend,helpful_ratio,is_black_friday,is_cyber_monday,is_thanksgiving_week,is_holiday_season,is_prime_day,is_sale_period
0,A32T2H8150OJLU,B00000JBLH,5.0,2004-09-03,2004,9,Friday,False,0,False,False,False,False,False,False
1,A3MAFS04ZABRGO,B00000JBLH,5.0,2007-12-15,2007,12,Saturday,True,0,False,False,False,False,False,False
2,A1F1A0QQP2XVH5,B00000JBLH,2.0,2011-01-01,2011,1,Saturday,True,0,False,False,False,False,False,False
3,A49R5DBXXQDE5,B00000JBLH,5.0,2006-04-19,2006,4,Wednesday,False,0,False,False,False,False,False,False
4,A2XRMQA6PJ5ZJ8,B00000JBLH,5.0,2013-08-04,2013,8,Sunday,True,0,False,False,False,False,False,False

In [118]:
cols = [
    "is_black_friday",
    "is_cyber_monday",
    "is_thanksgiving_week",
    "is_holiday_season",
    "is_prime_day",
    "is_sale_period"
]

for col in cols:
    print(f"\n{col}")
    print(df_combined[col].value_counts())
    print(f"null values: {df_combined[col].isna().sum()}")

is_black_friday
is_black_friday
False    106516
Name: count, dtype: int64
null values: 0

is_cyber_monday
is_cyber_monday
False    106516
Name: count, dtype: int64
null values: 0

is_thanksgiving_week
is_thanksgiving_week
False    105707
True        809
Name: count, dtype: int64
null values: 0

is_holiday_season
is_holiday_season
False    101865
True       4651
Name: count, dtype: int64
null values: 0

is_prime_day
is_prime_day
False    106234
True        282
Name: count, dtype: int64
null values: 0

is_sale_period
is_sale_period
False    100809
True       5707
Name: count, dtype: int64
null values: 0

In [119]:
df_combined.drop(
    columns=["is_black_friday", "is_cyber_monday"],
    inplace=True
)

In [120]:
cols = [col for col in df_combined.columns if col not in ["review", "summary"]]
df_combined[cols].head()

,reviewerID,asin,rating,review_date,review_year,review_month,day_of_week,is_weekend,helpful_ratio,is_thanksgiving_week,is_holiday_season,is_prime_day,is_sale_period
0,A32T2H8150OJLU,B00000JBLH,5.0,2004-09-03,2004,9,Friday,False,0,False,False,False,False
1,A3MAFS04ZABRGO,B00000JBLH,5.0,2007-12-15,2007,12,Saturday,True,0,False,False,False,False
2,A1F1A0QQP2XVH5,B00000JBLH,2.0,2011-01-01,2011,1,Saturday,True,0,False,False,False,False
3,A49R5DBXXQDE5,B00000JBLH,5.0,2006-04-19,2006,4,Wednesday,False,0,False,False,False,False
4,A2XRMQA6PJ5ZJ8,B00000JBLH,5.0,2013-08-04,2013,8,Sunday,True,0,False,False,False,False

In [121]:
cols = [
    "is_thanksgiving_week",
    "is_holiday_season",
    "is_prime_day",
    "is_sale_period"
]

for col in cols:
    print(f"\n{col}")
    print(df_combined[col].value_counts())
    print(f"null values: {df_combined[col].isna().sum()}")

is_thanksgiving_week
is_thanksgiving_week
False    105707
True        809
Name: count, dtype: int64
null values: 0

is_holiday_season
is_holiday_season
False    101865
True       4651
Name: count, dtype: int64
null values: 0

is_prime_day
is_prime_day
False    106234
True        282
Name: count, dtype: int64
null values: 0

is_sale_period
is_sale_period
False    100809
True       5707
Name: count, dtype: int64
null values: 0

In [122]:
pd.set_option("display.max_rows", None)

In [123]:
reviewer_stats = (
    df_combined.groupby("reviewerID")["rating"]
    .describe()
    .sort_values(by="count", ascending=False)
)

reviewer_stats.head(10)

,count,mean,std,min,25%,50%,75%,max
reviewerID,,,,,,,,
AGZZXSMMS4WRHHJRBUJZI4FZDHKQ,701.0,4.907275,0.415714,1.0,5.0,5.0,5.0,5.0
AH665SQ6SQF6DXAGYIQFCX76LALA,498.0,4.238956,0.635256,2.0,4.0,4.0,5.0,5.0
AHV6QCNBJNSGLATP56JAWJ3C4G2A,453.0,4.496689,0.566867,3.0,4.0,5.0,5.0,5.0
AGSP6LSQK32SQEJO3YVVNACPWMSQ,286.0,4.234266,0.520810,3.0,4.0,4.0,5.0,5.0
AF4P6A3SEKS2HCISWAKFZVIFM7NQ,263.0,3.939163,0.947126,1.0,3.0,4.0,5.0,5.0
AG73BVBKUOH22USSFJA5ZWL7AKXA,259.0,4.509653,0.684054,1.0,4.0,5.0,5.0,5.0
AF3ODW6NCKEVVTGZNFS6FUQYSGTQ,255.0,4.517647,0.864138,1.0,4.0,5.0,5.0,5.0
AH5HSMUMRJRDWBPFDQ6G3EAAOSFQ,230.0,4.691304,0.744947,1.0,5.0,5.0,5.0,5.0
AFTZWAK3ZHAPCNSOT5GCKQDECBTQ,228.0,3.894737,1.552990,1.0,2.0,5.0,5.0,5.0
AFZUK3MTBIBEDQOPAK3OATUOUKLA,202.0,4.737624,0.658258,1.0,5.0,5.0,5.0,5.0

In [124]:
# reviwers who posted more than 10 reviews 
reviewer_stats[reviewer_stats["count"] >= 10].shape[0]

2772

In [125]:
cols = [col for col in df_combined.columns if col not in ["review", "summary"]]
df_combined[cols].head()

,reviewerID,asin,rating,review_date,review_year,review_month,day_of_week,is_weekend,helpful_ratio,is_thanksgiving_week,is_holiday_season,is_prime_day,is_sale_period
0,A32T2H8150OJLU,B00000JBLH,5.0,2004-09-03,2004,9,Friday,False,0,False,False,False,False
1,A3MAFS04ZABRGO,B00000JBLH,5.0,2007-12-15,2007,12,Saturday,True,0,False,False,False,False
2,A1F1A0QQP2XVH5,B00000JBLH,2.0,2011-01-01,2011,1,Saturday,True,0,False,False,False,False
3,A49R5DBXXQDE5,B00000JBLH,5.0,2006-04-19,2006,4,Wednesday,False,0,False,False,False,False
4,A2XRMQA6PJ5ZJ8,B00000JBLH,5.0,2013-08-04,2013,8,Sunday,True,0,False,False,False,False

In [126]:
reviewer_date_range = df_combined.groupby("reviewerID")["review_date"].agg(
    first_review="min",
    last_review="max"
)

reviewer_date_range.head()

                      first_review last_review
reviewerID
A00473363TJ8YSZ3YAGG9   2013-01-06  2013-12-24
A04324702R5O7JRSQNVAH   2013-05-08  2013-05-24
A0678500JUN3N7KUG4PS    2013-12-03  2014-06-18
A100UD67AHFODS          2012-10-15  2014-07-11
A100WO06OQR8BQ          2008-12-26  2014-07-04

In [127]:
reviewer_date_range["review_span_days"] = (
    reviewer_date_range["last_review"] -
    reviewer_date_range["first_review"]
).dt.days

reviewer_date_range.head()

                      first_review last_review  review_span_days
reviewerID
A00473363TJ8YSZ3YAGG9   2013-01-06  2013-12-24               352
A04324702R5O7JRSQNVAH   2013-05-08  2013-05-24                16
A0678500JUN3N7KUG4PS    2013-12-03  2014-06-18               197
A100UD67AHFODS          2012-10-15  2014-07-11               634
A100WO06OQR8BQ          2008-12-26  2014-07-04              2016

In [128]:
df_combined["first_review"] = df_combined.groupby("reviewerID")["review_date"].transform("min")

In [129]:
df_combined["last_review"] = df_combined.groupby("reviewerID")["review_date"].transform("max")

In [130]:
df_combined["total_reviews_given"] = df_combined.groupby("reviewerID")["reviewerID"].transform("count")

In [131]:
df_combined["review_span_days"] = (
    df_combined["last_review"] - df_combined["first_review"]
).dt.days

In [132]:
cols = [col for col in df_combined.columns if col not in ["review", "summary"]]
df_combined[cols].head()

,reviewerID,asin,rating,review_date,review_year,review_month,day_of_week,is_weekend,helpful_ratio,is_thanksgiving_week,is_holiday_season,is_prime_day,is_sale_period,first_review,last_review,total_reviews_given,review_span_days
0,A32T2H8150OJLU,B00000JBLH,5.0,2004-09-03,2004,9,Friday,False,0,False,False,False,False,2004-09-03,2014-06-03,27,3560
1,A3MAFS04ZABRGO,B00000JBLH,5.0,2007-12-15,2007,12,Saturday,True,0,False,False,False,False,2004-10-11,2007-12-16,5,1161
2,A1F1A0QQP2XVH5,B00000JBLH,2.0,2011-01-01,2011,1,Saturday,True,0,False,False,False,False,2003-08-01,2014-06-17,30,3973
3,A49R5DBXXQDE5,B00000JBLH,5.0,2006-04-19,2006,4,Wednesday,False,0,False,False,False,False,2006-04-19,2012-01-17,5,2099
4,A2XRMQA6PJ5ZJ8,B00000JBLH,5.0,2013-08-04,2013,8,Sunday,True,0,False,False,False,False,2006-03-01,2014-05-13,12,2995

In [133]:
df_combined.columns

Index(['reviewerID', 'asin', 'review', 'rating', 'summary', 'review_date',
       'review_year', 'review_month', 'day_of_week', 'is_weekend',
       'helpful_ratio', 'is_thanksgiving_week', 'is_holiday_season',
       'is_prime_day', 'is_sale_period', 'first_review', 'last_review',
       'total_reviews_given', 'review_span_days'],
      dtype='object')

In [134]:
df_combined.dtypes

reviewerID                      object
asin                            object
review                          object
rating                         float64
summary                         object
review_date             datetime64[ns]
review_year                      int32
review_month                     int32
day_of_week                     object
is_weekend                        bool
helpful_ratio                    int64
is_thanksgiving_week              bool
is_holiday_season                 bool
is_prime_day                      bool
is_sale_period                    bool
first_review            datetime64[ns]
last_review             datetime64[ns]
total_reviews_given              int64
review_span_days                 int64
dtype: object

In [135]:
prime = (
    df_combined[df_combined["is_prime_day"]]
    .groupby("reviewerID")["total_reviews_given"]
    .max()
    .sort_values(ascending=False)
)

print("Maximum:")
print(prime.head(1))

print("\nMinimum:")
print(prime.tail(1))

Maximum:
reviewerID
AGZZXSMMS4WRHHJRBUJZI4FZDHKQ    701
Name: total_reviews_given, dtype: int64

Minimum:
reviewerID
AHTZPACLCJZLSKCPAKAQFGWHT3IA    1
Name: total_reviews_given, dtype: int64

In [136]:
thanks = (
    df_combined[df_combined["is_thanksgiving_week"]]
    .groupby("reviewerID")["total_reviews_given"]
    .max()
    .sort_values(ascending=False)
)

print("Maximum:")
print(thanks.head(1))

print("\nMinimum:")
print(thanks.tail(1))

Maximum:
reviewerID
AGZZXSMMS4WRHHJRBUJZI4FZDHKQ    701
Name: total_reviews_given, dtype: int64

Minimum:
reviewerID
AHZVRSD76YSY4TJXKSE7ZJMQFZSA    1
Name: total_reviews_given, dtype: int64

In [137]:
holiday = (
    df_combined[df_combined["is_holiday_season"]]
    .groupby("reviewerID")["total_reviews_given"]
    .max()
    .sort_values(ascending=False)
)

print("Maximum:")
print(holiday.head(1))

print("\nMinimum:")
print(holiday.tail(1))

Maximum:
reviewerID
AGZZXSMMS4WRHHJRBUJZI4FZDHKQ    701
Name: total_reviews_given, dtype: int64

Minimum:
reviewerID
AHZXXXPAJSJAX4SBPON5VHCD4YMQ    1
Name: total_reviews_given, dtype: int64

In [138]:
sale = (
    df_combined[df_combined["is_sale_period"]]
    .groupby("reviewerID")["total_reviews_given"]
    .max()
    .sort_values(ascending=False)
)

print("Maximum:")
print(sale.head(1))

print("\nMinimum:")
print(sale.tail(1))

Maximum:
reviewerID
AGZZXSMMS4WRHHJRBUJZI4FZDHKQ    701
Name: total_reviews_given, dtype: int64

Minimum:
reviewerID
AHAKYRPIQKX5M5JX6Q5KLE6EZSAQ    1
Name: total_reviews_given, dtype: int64